sonar.projectKey=u-metadata-airflow-apis
sonar.projectName=u-metadata-airflow-apis
sonar.organization=u-metadata
sonar.language=py

sonar.sources=umetadata_managed_apis
sonar.tests=tests
sonar.exclusions=umetadata_managed_apis/views/**,umetadata_managed_apis/plugin.py
sonar.python.xunit.reportPath=junit/test-results-*.xml
sonar.python.coverage.reportPaths=ci-coverage.xml
sonar.python.version=3.7,3.8,3.9
