CREATE DATABASE umetadata_db;
CREATE DATABASE airflow_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER 'umetadata_user'@'%' IDENTIFIED BY 'umetadata_password';
CREATE USER 'airflow_user'@'%' IDENTIFIED BY 'airflow_pass';
GRANT ALL PRIVILEGES ON umetadata_db.* TO 'umetadata_user'@'%' WITH GRANT OPTION;
GRANT PROCESS, USAGE ON *.* TO 'umetadata_user'@'%';
GRANT ALL PRIVILEGES ON airflow_db.* TO 'airflow_user'@'%' WITH GRANT OPTION;
GRANT PROCESS, USAGE ON *.* TO 'umetadata_user'@'%';
FLUSH PRIVILEGES;
commit;
